export default {
  nickname: 'Young',
  job: '前端开发',
  name: 'CYM',
  experience: '三年工作经验',
  wx: 'cymilyily',
  email: 'atlasyoung@163.com',
  mobile: '17692390522',
  github: 'http://github.com/cuiyiming1998',
  avatar: 'https://avatars.githubusercontent.com/u/25956970?v=4',
  address: 'Beijing, China',
  skills: [
    'JavaScript',
    'TypeScript',
    'Vue',
    'React',
    'vite',
    'Webpack',
    'TailwindCSS',
    'Unocss',
  ],
}
