export default {
  nickname: 'Young',
  name: 'CYM',
  experience: '三年工作经验',
  wx: 'cymilyily',
  email: 'atlasyoung@163.com',
  mobile: '17692390522',
  github: 'http://github.com/cuiyiming1998',
  avatar: 'https://avatars.githubusercontent.com/u/25956970?v=4',
  job: 'Frontend Engineer',
  birthday: '1998/05/22',
  description: 'Everything will be ok.',
  address: 'Beijing, China',
  skills: [
    'JavaScript',
    'TypeScript',
    'Vue',
    'React',
    'Vite',
    'Webpack',
    'TailwindCSS',
    'Unocss',
  ],
  projects: [
    {
      name: 'Vue3-mini',
      description: 'Minimum implementation of Vue3 source code.',
      iconName: 'i-carbon-logo-vue',
      url: 'https://github.com/cuiyiming1998/Vue3-mini',
    },
    {
      name: 'Algorithms-JavaScript',
      description: 'Writting Algorithms with JavaScript.',
      iconName: 'i-ion-construct',
      url: 'https://github.com/cuiyiming1998/algorithms-javascript',
    },
    {
      name: 'React-Source',
      description: 'Minimum implementation of React source code.',
      iconName: 'i-ion-logo-react',
      url: 'https://github.com/cuiyiming1998/react-source',
    },
    {
      name: 'Awesome-JavaScript',
      description: 'Implementation of JavaScript native APIs.',
      iconName: 'i-ion-logo-javascript',
      url: 'https://github.com/cuiyiming1998/awesome-javascript',
    },
    {
      name: 'Arco Design Admin',
      description: 'A back-end template based on Vue3, Vite and TypeScript(working on it).',
      iconName: 'i-ion-earth',
      url: 'https://github.com/cuiyiming1998/awesome-javascript',
    },
  ],
}
